services:
  web:
    build: .
    container_name: web_pj_1-web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:alpine
    container_name: web_pj_1-redis
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: web_pj_1-celery
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A app.worker worker --loglevel=info
